# Generated by Django 5.2.17 on 2026-09-04 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='Se usa en la dirección web de la categoría.', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='Se usa en la dirección web del producto.', max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.PositiveIntegerField(help_text='En centavos de peso. Un producto de $80.000 se guarda como 8000000.')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='existencias')),
                ('imagen', models.ImageField(blank=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True, help_text='Desmárcalo para ocultar el producto de la tienda sin borrarlo.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='catalogo.categoria', verbose_name='categoría')),
            ],
            options={
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['activo', 'categoria'], name='catalogo_pr_activo_01843d_idx')],
            },
        ),
    ]
