# Generated by Django 5.2.17 on 2026-09-04 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['-creado', '-id']},
        ),
    ]
