# Generated by Django 5.2.17 on 2026-09-05 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogo', '0002_alter_producto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='correo del comprador')),
                ('direccion_de_envio', models.TextField(verbose_name='dirección de envío')),
                ('total', models.PositiveBigIntegerField(help_text='En centavos, congelado al crear el pedido.')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de pago'), ('pagado', 'Pagado'), ('enviado', 'Enviado')], db_index=True, default='pendiente', max_length=20)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('pagado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_unitario', models.PositiveIntegerField(help_text='En centavos, al momento de la compra.')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items_de_pedido', to='catalogo.producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido')),
            ],
            options={
                'verbose_name': 'ítem del pedido',
                'verbose_name_plural': 'ítems del pedido',
            },
        ),
    ]
